// single comment
/**
 * double
 * comment
 */

//--------output types-------
    // -alart()
          alert('hello');
          console.log('hellow console');
          document.write('hello document');
// Data type

/**
 * -string
       -""
       -''

 * -number
       (-int,-dbl/floot)
       -5
       -60
       1.3
 * -boolean
       - true
       - false
 * -null
 * -undefined
 * -array
 * nan(not a number)
 * -object
 * 
 */


// document.write(typeof("doc1234"));

//var a =[10,"test",100];

// console.log(a[0]);

//var a ={
 //    name: 'userName',
 //     age:24,
 //     years:{
 //          SSC:2020
 //           HSC:2022
 //            }
 //       }

 /**
  * Variable
  *    -let
  *     -ver
  *      -const
  */

 var userName ="username";
var id = 12345;



 document.write("userName:" + username+ "<Br>" +"id:"+ id);


 //let userName = "let test"
// document.write(userName)